name: Frontend Verify
on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend
jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Yarn Install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn Install eslint
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install eslint
      - name: Eslint
        run: eslint . --exit .js
      - name: Test
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
