name: Frontend Verify
on:
  push:
    branches:
      - front-end
  pull_request:
    branches:
      - front-end
jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Yarn Install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Eslint
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Test
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test